In [0]:
import pandas as pd

In [0]:
dict_data = { "Name": ["Alice", "John", "Carol","Jane"],
      "Age": [25, 30, 22,27],
      "city": ["Cape Town", "Joburg", "Durban","Joburg"]
      }

df = pd.DataFrame(dict_data)   
print(df)

    Name  Age       city
0  Alice   25  Cape Town
1   John   30     Joburg
2  Carol   22     Durban
3   Jane   27     Joburg

In [0]:
df.head(2)

    Name  Age       city
0  Alice   25  Cape Town
1   John   30     Joburg

In [0]:
df.shape

(4, 3)

# Exploratory Data Analysis

Before doing anything with data, you need to understand what's in it. Pandas gives you quick summary tools.

# Loading data

It's like opening a spreadsheet, but with a single line of code instead of double-clicking a file.

In [0]:
df = pd.read_csv("retail_sales_dataset.csv")

df.head()

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30
3               4  2023-05-21  ...            500          500
4               5  2023-05-06  ...             50          100

[5 rows x 9 columns]

In [0]:
#how many rows and columns
df.shape

(1000, 9)

# Explore Data

In [0]:
#column names, data types, nulls
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [0]:
# stats: mean, min, max etc
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [0]:
df.columns

Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount'],
      dtype='object')

In [0]:
print(df["Total Amount"].sum())

456000

In [0]:
print(df["Total Amount"].mean())

456.0

Selecting Columns and rows

In [0]:
df["Product Category"]

0           Beauty
1         Clothing
2      Electronics
3         Clothing
4           Beauty
          ...
995       Clothing
996         Beauty
997         Beauty
998    Electronics
999    Electronics
Name: Product Category, Length: 1000, dtype: object

In [0]:
# Selecting mutiple columns
# df[["Product Category","Price per Unit"]]

access_column = ["Product Category","Price per Unit"]

print(df[access_column])

    Product Category  Price per Unit
0             Beauty              50
1           Clothing             500
2        Electronics              30
3           Clothing             500
4             Beauty              50
..               ...             ...
995         Clothing              50
996           Beauty              30
997           Beauty              25
998      Electronics              50
999      Electronics              30

[1000 rows x 2 columns]

In [0]:
#selecting rows by position - like a list index
df.iloc[0] #first row

Transaction ID               1
Date                2023-11-24
Customer ID            CUST001
Gender                    Male
Age                         34
Product Category        Beauty
Quantity                     3
Price per Unit              50
Total Amount               150
Name: 0, dtype: object

In [0]:
df.iloc[0:3] #first 3 rows

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30

[3 rows x 9 columns]

In [0]:
 df["Age"] < 20

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Age, Length: 1000, dtype: bool

In [0]:
#select row by condition

# df[df["Age"] < 20]

conditions = df["Age"] < 20 

df[conditions]

     Transaction ID        Date  ... Price per Unit Total Amount
15               16  2023-02-17  ...            500         1500
21               22  2023-10-15  ...             50          100
36               37  2023-05-23  ...             25           75
57               58  2023-11-13  ...            300         1200
61               62  2023-12-27  ...             50          100
73               74  2023-11-22  ...            500         2000
85               86  2023-11-08  ...             30           90
116             117  2023-03-15  ...            500         1000
147             148  2023-05-09  ...             30           60
168             169  2023-11-17  ...            500         1500
180             181  2023-11-03  ...            300         1200
256             257  2023-02-19  ...            500         2000
265             266  2023-12-01  ...             30           60
282             283  2023-05-08  ...            500          500
299             300  2023-01-31  ...             50          200
302             303  2023-01-02  ...             30           90
304             305  2023-05-16  ...             30           30
325             326  2023-09-15  ...             25           75
363             364  2023-08-23  ...            500          500
390             391  2023-01-05  ...             25           50
411             412  2023-09-16  ...            500         2000
460             461  2023-03-25  ...            500         1000
468             469  2023-05-08  ...             25           75
483             484  2023-01-13  ...            300         1200
513             514  2023-03-01  ...            300          300
529             530  2023-02-05  ...             30          120
532             533  2023-11-16  ...            500         1500
537             538  2023-09-17  ...             50          150
555             556  2023-06-04  ...             50           50
593             594  2023-09-01  ...            300          600
594             595  2023-11-09  ...            500         2000
600             601  2023-04-10  ...             30           30
627             628  2023-11-01  ...             50          200
676             677  2023-10-27  ...            500         1500
678             679  2023-01-11  ...             30           90
708             709  2023-07-21  ...            500         1000
713             714  2023-02-12  ...            500          500
811             812  2023-11-12  ...             25           75
836             837  2023-07-01  ...             30           90
846             847  2023-04-08  ...            300         1200
978             979  2023-01-02  ...             25           25
984             985  2023-05-30  ...             25           50

[42 rows x 9 columns]

# simple summaries & grouping

In [0]:
#count how many transactions are in each product category
df["Product Category"].value_counts()

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [0]:
#average total amount by Product Category

df.groupby("Product Category")["Total Amount"].mean()

Product Category
Beauty         467.475570
Clothing       443.247863
Electronics    458.786550
Name: Total Amount, dtype: float64