In [0]:
import pandas as pd

In [0]:
df = pd.read_csv("retail_sales_dataset.csv")

df.head()

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30
3               4  2023-05-21  ...            500          500
4               5  2023-05-06  ...             50          100

[5 rows x 9 columns]

# Explore Categories

In [0]:
df["Product Category"].unique()

array(['Beauty', 'Clothing', 'Electronics'], dtype=object)

In [0]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [0]:
#count unique values

df["Product Category"].nunique()

3

In [0]:
# Frequency Counts
df["Product Category"].value_counts()

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [0]:
df["Gender"].value_counts()

Gender
Female    510
Male      490
Name: count, dtype: int64

# sorting and ranking

In [0]:
df.head()

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30
3               4  2023-05-21  ...            500          500
4               5  2023-05-06  ...             50          100

[5 rows x 9 columns]

In [0]:
df.sort_values(by="Total Amount", ascending=False).head(10)

     Transaction ID        Date  ... Price per Unit Total Amount
571             572  2023-04-20  ...            500         2000
88               89  2023-10-01  ...            500         2000
502             503  2023-10-25  ...            500         2000
560             561  2023-05-27  ...            500         2000
831             832  2023-09-11  ...            500         2000
807             808  2023-04-01  ...            500         2000
576             577  2023-02-13  ...            500         2000
945             946  2023-05-08  ...            500         2000
446             447  2023-07-06  ...            500         2000
734             735  2023-10-04  ...            500         2000

[10 rows x 9 columns]

# Groupby analytics

In [0]:
#total revenue by category
df.groupby("Product Category")["Total Amount"].sum()

Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

In [0]:
#average spend by gender
df.groupby("Gender")["Total Amount"].mean()

Gender
Female    456.549020
Male      455.428571
Name: Total Amount, dtype: float64

In [0]:
df["Transaction ID"]

0         1
1         2
2         3
3         4
4         5
       ...
995     996
996     997
997     998
998     999
999    1000
Name: Transaction ID, Length: 1000, dtype: int64

df.groupby("Product Category")

- split into groups
df1

df2

df3

- access data in the colum per group
df1["Transaction ID"]

df2["Transaction ID"]

df3["Transaction ID"]


- Aggregate values in the columns per group
df1["Transaction ID"].count()

df2["Transaction ID"].count()

df3["Transaction ID"].count()

In [0]:
#transaction count by category
df.groupby("Product Category")["Transaction ID"].count()

Product Category
Beauty         307
Clothing       351
Electronics    342
Name: Transaction ID, dtype: int64

In [0]:
df.groupby("Product Category")["Total Amount"].agg(["sum", "mean","max","min","count"])

                     sum        mean   max  min  count
Product Category
Beauty            143515  467.475570  2000   25    307
Clothing          155580  443.247863  2000   25    351
Electronics       156905  458.786550  2000   25    342

# Feature Engineering

In [0]:
df.head()

   Transaction ID        Date  ... Price per Unit Total Amount
0               1  2023-11-24  ...             50          150
1               2  2023-02-27  ...            500         1000
2               3  2023-01-13  ...             30           30
3               4  2023-05-21  ...            500          500
4               5  2023-05-06  ...             50          100

[5 rows x 9 columns]

In [0]:
#create discount column

df["Discount"] = df["Total Amount"] * 0.10

df.head()

   Transaction ID        Date  ... Total Amount Discount
0               1  2023-11-24  ...          150     15.0
1               2  2023-02-27  ...         1000    100.0
2               3  2023-01-13  ...           30      3.0
3               4  2023-05-21  ...          500     50.0
4               5  2023-05-06  ...          100     10.0

[5 rows x 10 columns]

In [0]:
df["Final Amount"] = df["Total Amount"] - df["Discount"]

df.head()

   Transaction ID        Date Customer ID  ... Total Amount  Discount Final Amount
0               1  2023-11-24     CUST001  ...          150      15.0        135.0
1               2  2023-02-27     CUST002  ...         1000     100.0        900.0
2               3  2023-01-13     CUST003  ...           30       3.0         27.0
3               4  2023-05-21     CUST004  ...          500      50.0        450.0
4               5  2023-05-06     CUST005  ...          100      10.0         90.0

[5 rows x 11 columns]

# Mini Exercise

Challenge??


Using pandas, answer:

1. which product category has
    - highest revenue
    - lowest revenue
2. Which Gender spendds more on average
3. show top 5 transactions
4. Assuming the Total amount excludes VAT, create:
    - VAT column
    - Final Amount column
5. Average Transaction value
6. Most common product category